config/routes.rb
Rails.application.routes.draw do

   root 'application#hello'

  resources :books

  get 'projects/search', to: 'projects#search', as: 'projects_search'
  get 'projects',to: 'projects#index'

end

app/models/project.rb
class Project
  # attr_accessible :keywords, :location
  def self.search(search)
       #find(:all, :conditions => ['location LIKE ?',search])
    search = Cb.job.search_criteria.location(params[:search]).radius(10).search()

    search.each do |job|
      puts job.title
      puts job.company_name
      puts job.instance_variables
    end

  else
      find(:all)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello, world"

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    #@books = Book.all
  end
end

app/controllers/projects_controller.rb
require 'cb'
Cb.configure do |config|
  config.dev_key    = 'WDHV2ZS6091Z9BQC0R04'
  config.time_out   = 5
end


class ProjectsController < ApplicationController
  def index
  end

  def search
    criteria = {}
    criteria[:Location] = params[:location]
    criteria[:Keywords] = params[:keywords]
    @job_results = Cb.job.search criteria
    #binding.pry #Cannot be the last line of executed code

    #@job_results = search
    #@results = Project.search params[:keywords]
  end

  def getCompanyComments
    Cb::Requests::Company::Find.new()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_path_helper.rb
#require 'core_ext/string'
#require 'cgi'

module JobsPathHelper
  def friendly_jobs_link(search_attributes = {})
    search_attrs = search_attrs_to_hash(search_attributes)

    search_attrs[:keywords] = transform_url_param(search_attributes[:keywords])
    search_attrs[:location] = transform_url_param(search_attributes[:location])

    if search_attrs[:keywords].blank? && search_attrs[:location].blank?
      jobs_path search_attrs
    elsif search_attributes[:keywords].blank?
      jobs_location_path search_attrs
    elsif search_attributes[:location].blank?
      jobs_keyword_path search_attrs
    else
      jobs_keyword_location_path search_attrs
    end
  rescue
    jobs_path
  end

  private

  def search_attrs_to_hash(search_attributes)
    search_attrs = if search_attributes.respond_to?(:to_h)
                     search_attributes.to_h
                   elsif search_attributes.respond_to?(:to_hash)
                     search_attributes.to_hash
                   else
                     search_attributes || {}
                   end
    search_attrs.symbolize_keys!
    search_attrs
  end

  def transform_url_param(url_param)
    url_param = nil if url_param.blank?
    if url_param.present?
      unless url_param.ascii_only?
        url_param = CGI.escape(url_param)
      end
      url_param = url_param.to_slug
    end
    url_param
  end
end

app/views/books/index.html.haml
%h1 Listing Books

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/projects/index.html.haml
%h2{:align => "center"} Job Search
%body
-#%form{:action => "search", :method => "get" ,:controller => "projects"}
= form_tag(projects_search_path, :method => "get", id: "search-form", action: "search") do
  .row
    .column
      Keywords
  .row
    .column
      -#%input{:id => "keywords",:class => "search-field",:type => "text",:align =>"center",:style => "width:100%",:name => "keywords"}
      = text_field_tag :keywords, params[:keywords], class: "search-field", placeholder: "Search Keywords"
  .row
    .column
      Location
  .row
    .column
      -#%input{:id => "location",:class => "search-field",:type => "text",:align =>"center",:style => "width:100%",:name => "location"}
      = text_field_tag :location, params[:location], class: "search-field", placeholder: "Search Location"
  .row
    .column
      %input{:type => "submit",:align =>"center",:style => "width:100%"}

app/views/projects/search.html.erb
<html lang="en"><head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title>Swipe a Job</title>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" %>
    <%= javascript_include_tag "application" %>
    <script>
        $(document).ready(function() {
            Slider = $('#slider').Swipe({
//                auto: 3000,
//                continuous: true
            }).data('Swipe');

            $('.next').on('click', Slider.next);
            $('.prev').on('click', Slider.prev);
        });
    </script>

</head>

<body>

<div class="demo-wrapper">
    <div id="slider" class="swipe" style="visibility: visible;">
        <div class="swipe-wrap" style="width: 3000px; background-color: #ffffff">
            <% (@job_results).models.jobs.each do |job| %>
            <div data-index="0" style="width: 600px; left: 0px; transition-duration: 300ms; -webkit-transition-duration: 300ms; -webkit-transform: translate(-600px, 0px) translateZ(0px);">
              <tr>
              <td><div id="headerBar"><h4 align="center" style="color:#ffffff"><%= job.company_name %></h4></div></td>
              <td><h6><strong>Location:</strong> <%= job.location %></h6></td>
              <td><h6><strong>Job Title:</strong> <%= job.title %></h6></td>
              </tr>
            </div>
            <% end %>

        </div>

        <span class="nav prev">Prev</span>
        <span class="nav next">Next</span>

    </div>
</div>


</body></html>